services:
  vm:
    build: ./qemu
    container_name: qemu-ubuntu-novnc
    environment:
      RAM_MB: "8192"
      CPU_CORES: "4"
      DISK_SIZE: "512G"
      ISO_URL: "https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-desktop-amd64.iso"
      ISO_PATH: "/storage/ubuntu.iso"
      ISO_SHA256: ""
      BOOT_MODE: "install"
      VNC_ADDR: "0.0.0.0"
      VNC_PORT: "5900"
      NOVNC_PORT: "6080"
      DISPLAY_NUM: "0"
      VM_NAME: "ubuntu"
      DISK_PATH: "/storage/ubuntu.qcow2"
    volumes:
      - /tmp:/storage
    ports:
      - "5900:5900"
      - "6080:6080"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: unless-stopped
    stdin_open: true
    tty: true
